---
title: "42-predominant-isoform"
output: html_document
---


```{r}
library(tidyverse)
```

https://raw.githubusercontent.com/epigeneticstoocean/2018_L18-adult-methylation/main/data/whole_tx_table.csv



## Set variables

```{r set-variables}
# Vectors for subsetting samples by different groups
controls <- c("S13M", "S16F", "S19F", "S39F", "S44F", "S52F", "S53F", "S54F", "S64M", "S6M", "S76F", "S7M")
exposed <- c("S12M", "S22F", "S23M", "S29F", "S31M", "S35F", "S36F", "S3F", "S41F", "S48M", "S50F", "S59M", "S77F", "S9M")
controls_males <- c("S13M", "S64M", "S6M", "S7M")
exposed_males <- c("S12M", "S23M", "S31M", "S48M", "S59M", "S9M")
controls_females <- c("S16F", "S19F", "S39F", "S44F", "S52F", "S53F", "S54F", "S76F")
exposed_females <- c("S22F", "S29F", "S35F", "S36F", "S3F", "S41F", "S50F", "S77F")
```

```{r}
tx_exp <- read.csv("https://raw.githubusercontent.com/epigeneticstoocean/2018_L18-adult-methylation/main/data/whole_tx_table.csv")
```

```{r}
tx_exp
```



```{r}
tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  pivot_longer(cols = c(3:28)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value))
```




```{r}
tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  pivot_longer(cols = c(3:28)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp))
```


```{r}
predom_all <- tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  pivot_longer(cols = c(3:28)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp))
```

```{r}
write.table(predom_all, file = "../output/42-predominant-isoform/predom_iso-all.txt",quote = F, row.names = F, sep = "\t")
```


Now can we do it for each "treatment"
Let first just try to separate males and females

females first....


```{r}
tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  select(ends_with(c("name", "name", "F"))) %>%
  pivot_longer(cols = c(3:18)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp)) %>%
  write.table(file = "../output/42-predominant-isoform/predom_iso-FEMALE.txt",quote = F, row.names = F, sep = "\t")
```


Males

```{r}
tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  select(ends_with(c("name", "name", "M"))) %>%
  pivot_longer(cols = c(3:12)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp)) %>%
  write.table(file = "../output/42-predominant-isoform/predom_iso-MALE.txt",quote = F, row.names = F, sep = "\t")
```


Lets join male and female.

```{r}
mpre <- tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  select(ends_with(c("name", "name", "M"))) %>%
  pivot_longer(cols = c(3:12)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp))
```


```{r}
fpre <- tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  select(ends_with(c("name", "name", "F"))) %>%
  pivot_longer(cols = c(3:18)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp))
```

```{r}
full_join(mpre, fpre, by = "gene_name") %>%
  filter(t_name.x!=t_name.y) %>%
  filter(abs(Predom_exp.x - Predom_exp.y) > 100)
```
```{r}
anti_join(mpre, fpre, by = "t_name")
```

```{r}
anti_join(fpre, mpre, by = "t_name")
```







NOW withing MALES can we see difference in OA....


EXPOSED
```{r exposed-males-predominant-isoforms}
tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  select(ends_with(c("name", "name", exposed_males))) %>%
  pivot_longer(cols = c(3:length(exposed_males) + 2)) %>% # Adds length of vector "exposed males" + "name" + "name" from previous line
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp)) %>% 
  write.table(file = "../output/42-predominant-isoform/predom_iso-exposed-MALE.txt",quote = F, row.names = F, sep = "\t")
```



CONTROL
```{r controls-males-predominant-isoforms}
mco <- tx_exp %>%
  select(starts_with(c("gene_name", "t_name", "FPKM"))) %>%
  select(ends_with(c("name", "name", controls_males))) %>%
  pivot_longer(cols = c(3:length(controls_males) + 2)) %>%
  group_by(gene_name, t_name) %>%
  summarise(Predom_exp = mean(value)) %>%
  group_by(gene_name) %>%
  slice(which.max(Predom_exp)) %>% 
  write.table(file = "../output/42-predominant-isoform/predom_iso-controls-MALE.txt",quote = F, row.names = F, sep = "\t")
```


```{r}
full_join(mco, mex, by = "gene_name") %>%
  filter(t_name.x!=t_name.y) %>%
  filter(abs(Predom_exp.x - Predom_exp.y) > 10)
```
