---
title: "68 exon expression"
author: Steven Roberts
date: "`r format(Sys.time(), '%d %B, %Y')`" 
output: 
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
  # github_document:
  #   toc: true
  #   toc_depth: 3
  #   number_sections: true
  #   html_preview: true
---

```{r}
library(BiocManager)
#BiocManager::install("WGCNA")
```


```{r setup, include=FALSE}
#library(kableExtra)
# library(DESeq2)
# library(pheatmap)
# library(RColorBrewer)
# library(data.table)
#library(DT)
# library(Biostrings)
#library(methylKit)
library(WGCNA)
library(data.table) # for data manipulation
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = TRUE,     # Hide warnings
  message = TRUE,     # Hide messages
  fig.width = 6,       # Set plot width in inches
  fig.height = 4,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)
```

```{r}
datExpr <- fread("../output/68-female-exon-fold/logfc.txt")
```

```{r}
rownames(datExpr) <- datExpr$GeneID
names(datExpr)
genes<-datExpr$GeneID
datExpr <- datExpr[ , -1, with = FALSE]
```

Transpose to put "samples" or exon in rows and genes in columns. Put gene ID in row names. 
```{r}
datExpr <- t(datExpr) 
datExpr<-as.data.frame(datExpr)

names(datExpr)<-genes
```

```{r}
sampleTree = hclust(dist(datExpr), method = "average")
plot(sampleTree, main = "Sample clustering to detect outliers", sub = "", xlab = "", cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)

```

```{r}
powers = c(1:10)
sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 5)
plot(sft$fitIndices[,1], -log(sft$fitIndices[,3]), pch = 19, xlab="Soft Threshold (power)", ylab="-log10 scale free topology model fit", type="n")
text(sft$fitIndices[,1], -log(sft$fitIndices[,3]), labels=powers, cex=0.5)
abline(h = -log(0.9), col = "red")

```

```{r}
softPower = 4 # example value, adjust based on your plot
adjacency = adjacency(datExpr, power = softPower)
TOM = TOMsimilarity(adjacency)
dissTOM = 1-TOM
geneTree = hclust(as.dist(dissTOM), method = "average")

dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM, deepSplit = 2, pamRespectsDendro = FALSE, minClusterSize = 100)

table<-as.data.frame(table(dynamicMods)) #list modules and respective sizes
table(dynamicMods)
```


```{r}
# Assuming 'dynamicMods' is your vector of module assignments from cutreeDynamic
moduleLabels = dynamicMods

```

```{r}
#Calculate eigengenes
MEList = moduleEigengenes(datExpr, colors = moduleLabels, softPower = 4)
MEs = MEList$eigengenes

#Calculate dissimilarity of module eigengenes
MEDiss = 1-cor(MEs)

#merge to 85% similar 
MEDissThres= 0.1 #merge modules that are 85% similar

merge= mergeCloseModules(datExpr, moduleLabels, cutHeight= MEDissThres, verbose =3)

mergedColors= merge$colors
mergedMEs= merge$newMEs

moduleLabels=mergedColors
moduleColors = mergedColors # Rename to moduleColors
MEs = mergedMEs;
ncol(MEs) #How many modules do we have now?

table(mergedColors)
table<-as.data.frame(table(mergedColors))
table
```

We have 26 modules after merging to 85% similarity. The table shows number of genes in each module.

Plot module expression across exon location. 
```{r}
head(MEs)
names(MEs)
Strader_MEs <- MEs
Strader_MEs$exon <- c("2", "3", "4", "5", "6")
head(Strader_MEs)
```
```{r}
plot_MEs<-Strader_MEs%>%
  gather(., key="Module", value="Mean", ME4:ME28)
```


Plot module expression across exon location. 
```{r}
library(ggplot2)
library(tidyverse)

expression_plot<-plot_MEs%>%
  group_by(Module, exon) %>%
  
  ggplot(aes(x=exon, y=Mean)) +
  facet_wrap(~Module)+
  geom_point() +
  geom_line(group=1)+
  #ylim(-0.5,1) +
  ylab("Mean Module Eigenegene") +
  geom_hline(yintercept = 0, linetype="dashed", color = "grey")+
  theme_classic(); expression_plot
```







```{r}
genesInBlueModule = names(moduleLabels[moduleLabels == "blue"])

```


```{r}
datExprBlueModule = datExpr[genesInBlueModule, ]

```

